### ISSUE TITLE
Runtime error with Particle Photon board setup

### ISSUE THREAD

**Issue by valeryjacobs** [voodootikigod/voodoospark#56]
For a demo that previously was working fine (2 weeks ago) I now see the error below appear when my NodeJS code starts waiting for the 'ready' event.

This is how the code start off
var board = new five.Board({
  io: new Particle({
    token: token,
    deviceId: deviceId
  })
});

board.on("ready", function() {
      //It doesn't get here but show the error below:

I tried using Johnny-five 0.8.104 and 0.8.106. And I'm using this firmware on the proton: https://raw.githubusercontent.com/voodootikigod/voodoospark/master/firmware/voodoospark.cpp

Error message:

1446152480066 Device(s) particle-io
1446152481002 Connected particle-io
1446152491006 Device or Firmware Error A timeout occurred while connecting to the Board.

Please check that you've properly flashed the board with the correct firmware.
See: https://github.com/rwaldron/johnny-five/wiki/Getting-Started#trouble-shooting
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Board.emit (events.js:87:13)
    at Board.log (c:\DemoPhoton3\node_modules\johnny-five\lib\board.js:629:8)
    at Board.(anonymous function) [as error] (c:\DemoPhoton3\node_modules\johnny-five\lib\board.js:640:14)
    at Board.<anonymous> (c:\DemoPhoton3\node_modules\johnny-five\lib\board.js:411:14)
    at Timer.listOnTimeout (timers.js:119:15)

Any ideas? Again, this was all working fine before.

**Comment by rwaldron** [comment]
This is likely not a bug in voodoospark. Can you post the entire code that you're having issues with? Also, please upgrade to the latest version of Johnny-Five
